### ISSUE TITLE
Copied Code:

### ISSUE THREAD

**Issue by IamDurant** [UltimateHackers/Breacher#2]
Hey there, Ultimate Hackers, your XSStrike was awesome. But when I had a look at this, I was quite disappointed. It was fully copied shit from [here](https://dl.packetstormsecurity.net/UNIX/utilities/AdminpageFinder.py.txt) with small modifications. Do you consider it fair to copy paste someone's hard work? Don't u feel guilty. Well if I had, I would have felt hell lotta guilty. Dunno your intentions, but you havent been at all good. Doing a fucking copy paste, isnt good eh?

**Comment by UltimateHackers** [comment]
Hello Mr. Code Guardian,
I didn't copy code from anywhere, if you think only one people in the world should be allowed to use python libraries and HTTP response codes than you are probably retarded.

**Comment by the-Infected-Drake** [comment]
Dunno... But I guess insulting me, satisfies you a lot. Well it satisfies the fact that, you are copy-pasting dick, as each and every line there is copied frim the url I gave, except for the paths which you had changed...  XD... Good luck being a ultimate...

**Comment by IamDurant** [comment]
Dont about that, but yeah, if insulting me gives you a good feeling that you are awesome, and you have successfully proven ur code as ur own, then it okay with you. Stay happy kid...

And ya dont get cocky over it, each and every line of the code is ditto same to the the file on packetstorm, exept for the page paths which you have changed...

**Comment by IamDurant** [comment]
Anyways you have changed the whole code... Now it feels good that u have something of ur own... :)

**Comment by UltimateHackers** [comment]
Have fun trying to defame people but we are out of your reach mate.
Shove this code up your ass
