### ISSUE TITLE
Error in file "breacher.py" on line 17

### ISSUE THREAD

**Issue by amitaknkpt** [UltimateHackers/Breacher#4]
C:\Users\Foo\Downloads\Breacher-master\Breacher-master>python breacher.py -u foobar.org --type php --fast
  File "breacher.py", line 17
    \033[37mMade with \033[91m<3\033[37m By D3V\033[1;m"""
                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""\033[1;34m______   ______ _______ _______ _______ _     _ _______  ______
|_____] |_____/ |______ |_____| |       |_____| |______ |_____/
|_____] |    \_ |______ |     | |_____  |     | |______ |    \_

                          \033[37mMade with \033[91m<3\033[37m By D3V\033[1;m""")?

**Comment by UltimateHackers** [comment]
Its not compatible with python3.
